#!/usr/bin/env bash
# Neovim shared-config regression: plugin discovery, startup ordering, and
# the DMS-only colorscheme guard.
#
# Root cause it pins: lua/plugins/base46.lua used to force LazyVim's
# colorscheme to "dms", whose implementation (colors/dms.lua plus
# lua/lualine/themes/dms.lua) is generated by DMS on Fedora and is NOT in
# this repo. Any host without those files (Arch/Caelestia, fresh clones)
# logged `not found in runtime path: "colors/dms.*"` and fell back to
# habamax behind a "Could not load your colorscheme" error. The spec now
# selects "dms" only when the generated file exists and otherwise keeps
# LazyVim's bundled default (tokyonight).
#
# Static checks always run. Headless checks need the nvim binary plus
# read-only installed lazy plugin sources (explicitly allowed for these
# tests); otherwise they SKIP with SEAM PENDING instead of touching the
# network or live data paths.
set -euo pipefail

TEST_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly TEST_DIR
# shellcheck disable=SC1091 # sandbox harness computes source paths at runtime; static following is impossible by design
# shellcheck source=tests/lib/test-arch-isolation.sh
source "${TEST_DIR}/lib/test-arch-isolation.sh"

REPO="${TEST_ARCH_REPO_ROOT}"
SPEC="${REPO}/home/.config/nvim/lua/plugins/base46.lua"
LAZY="${REPO}/home/.config/nvim/lua/config/lazy.lua"

nvim_die() {
  printf 'test-nvim-loading: %s\n' "$*" >&2
  exit 1
}

# --- Static: discovery (no editor needed). ---
[[ -f ${SPEC} && -f ${LAZY} ]] || nvim_die 'missing nvim spec files in the repo'
# base46 stays eager: DMS colors/dms.lua requires it on the rtp before the
# colorscheme applies, and lualine's generated dms theme needs its _base46.
grep -Fq '"AvengeMedia/base46"' "${SPEC}" || nvim_die 'base46 plugin spec missing'
grep -Fq 'lazy = false' "${SPEC}" || nvim_die 'base46 must stay eager (lazy = false)'
grep -Fq 'priority = 1000' "${SPEC}" || nvim_die 'base46 startup priority missing'
# The LazyVim colorscheme override must stay conditional on the
# DMS-generated file; an unconditional override reintroduces the Arch break.
grep -Fq 'colorscheme = "dms"' "${SPEC}" || nvim_die 'dms colorscheme override missing'
grep -Fq 'colors/dms.lua' "${SPEC}" || nvim_die 'dms colorscheme guard missing'
grep -Fq 'filereadable' "${SPEC}" || nvim_die 'dms colorscheme guard missing'

# --- Static: startup ordering (lazyvim.plugins imports before user plugins). ---
lazyvim_line="$(grep -n 'import = "lazyvim.plugins"' "${LAZY}" | head -n 1 | cut -d: -f1)"
plugins_line="$(grep -n 'import = "plugins"' "${LAZY}" | head -n 1 | cut -d: -f1)"
[[ -n ${lazyvim_line} && -n ${plugins_line} ]] || nvim_die 'lazy import order unreadable'
((lazyvim_line < plugins_line)) || nvim_die 'lazyvim.plugins must import before plugins'

# --- Headless: needs the editor plus installed plugin sources. ---
command -v nvim >/dev/null 2>&1 || { printf 'SEAM PENDING: nvim not installed\n'; exit 3; }
LIVE_LAZY="${TEST_ARCH_LIVE_HOME}/.local/share/nvim/lazy"
if [[ ! -d ${LIVE_LAZY}/lazy.nvim || ! -d ${LIVE_LAZY}/LazyVim || ! -d ${LIVE_LAZY}/base46 || ! -d ${LIVE_LAZY}/tokyonight.nvim ]]; then
  printf 'SEAM PENDING: installed lazy plugin sources absent (no network fetch allowed)\n'
  exit 3
fi

# --- Static: dependency/version compatibility against those sources. ---
grep -Fq '_DMS_SUPPORT' "${LIVE_LAZY}/base46/lua/base46/init.lua" \
  || nvim_die 'installed base46 lacks DMS support the dms theme requires'
for symbol in get_builtin_theme theme_harmonize theme_set_bg 'M.load'; do
  grep -Fq "${symbol}" "${LIVE_LAZY}/base46/lua/base46/init.lua" \
    || nvim_die "installed base46 lacks ${symbol} the dms theme calls"
done
grep -Fq 'vim.cmd.colorscheme(M.colorscheme)' "${LIVE_LAZY}/LazyVim/lua/lazyvim/config/init.lua" \
  || nvim_die 'installed LazyVim no longer applies a string colorscheme option'

test_arch_make_sandbox

# One isolated root per scenario: temp HOME/XDG only, live paths never used.
run_scenario() {
  local name=$1 with_dms=$2
  local root="${TEST_ARCH_SANDBOX}/${name}"
  mkdir -p -- "${root}/config" "${root}/data/nvim" "${root}/state" "${root}/cache" "${root}/home" \
    || nvim_die "cannot create ${name} sandbox"
  cp -a -- "${REPO}/home/.config/nvim" "${root}/config/nvim" \
    || nvim_die "cannot stage repo nvim config for ${name}"
  cp -a -- "${LIVE_LAZY}" "${root}/data/nvim/lazy" \
    || nvim_die "cannot stage plugin sources for ${name}"
  if [[ ${with_dms} == yes ]]; then
    # Stub the DMS-generated colorscheme: proves selection picks "dms" when
    # the file exists, without needing DMS, settings, or wallpaper state.
    mkdir -p -- "${root}/config/nvim/colors" || nvim_die "cannot stage ${name} colors"
    printf 'vim.g.colors_name = "dms"\n' >"${root}/config/nvim/colors/dms.lua" \
      || nvim_die "cannot write ${name} dms stub"
  fi
  HOME="${root}/home" XDG_CONFIG_HOME="${root}/config" XDG_DATA_HOME="${root}/data" \
    XDG_STATE_HOME="${root}/state" XDG_CACHE_HOME="${root}/cache" \
    nvim --headless -V9"${root}/startup.log" \
      +'lua local ok, b = pcall(require, "base46"); print("NVIMPROBE base46:" .. tostring(ok and b._DMS_SUPPORT))' \
      +'lua print("NVIMPROBE colors:" .. tostring(vim.g.colors_name))' \
      +'qa!' >"${root}/probe.out" 2>&1 \
    || nvim_die "headless nvim failed for ${name}"
  printf '%s' "${root}"
}

# Arch/Caelestia shape: pure repo, no generated files -> bundled default.
arch_root="$(run_scenario arch no)"
grep -q 'NVIMPROBE base46:true' "${arch_root}/probe.out" \
  || nvim_die 'base46 did not load eagerly in the pure-repo scenario'
grep -q 'NVIMPROBE colors:tokyonight' "${arch_root}/probe.out" \
  || nvim_die 'pure-repo scenario did not keep the bundled tokyonight default'
grep -q 'colors/dms' "${arch_root}/startup.log" \
  && nvim_die 'pure-repo scenario still looks up the absent dms colorscheme'

# Fedora/DMS shape: generated file present -> dms, as before.
dms_root="$(run_scenario dms yes)"
grep -q 'NVIMPROBE colors:dms' "${dms_root}/probe.out" \
  || nvim_die 'generated-dms scenario did not select the dms colorscheme'

printf 'nvim loading: discovery, ordering, and colorscheme guard hold (arch=tokyonight, dms=dms).\n'
